name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increase the timeout to 60 minutes
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install CUDA driver
      run: |
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        sudo sh -c 'echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
        sudo apt-get update
        sudo apt-get install -y cuda-drivers
    - name: Install build dependencies
      run: |
        sudo apt-get install -y build-essential
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel Cython
    - name: Print working directory
      run: pwd
    - name: List contents of current directory
      run: ls -la
    - name: Install project in editable mode
      run: |
        pip install pylint
        python -m pip install -e .
    - name: Verify installation
      run: |
        python -c "import spio.cuda.driver; print('spio.cuda.driver imported successfully')"
    - name: List installed packages
      run: pip list
    - name: List built extensions
      run: ls -R .
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=pylintrc $(git ls-files '*.py')
